/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package simulacroCalculadora.gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import simulacroCalculadora.dto.Operacion;
import simulacroCalculadora.logica.LogicaOperaciones;

/**
 *
 * @author Robert
 */
public class JDialogOperaciones extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogOperaciones.class.getName());

    /**
     * Creates new form JDialogOperaciones
     */
    public JDialogOperaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jComboBoxOperacion = new javax.swing.JComboBox<>();
        jLabelOperacion = new javax.swing.JLabel();
        jLabelNum1 = new javax.swing.JLabel();
        jTextFieldNum1 = new javax.swing.JTextField();
        jLabelNum2 = new javax.swing.JLabel();
        jSpinnerNum2 = new javax.swing.JSpinner();
        jLabelOperacionImg = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(204, 204, 0));

        jComboBoxOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División", "Potencia" }));
        jComboBoxOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperacionActionPerformed(evt);
            }
        });

        jLabelOperacion.setText("Operación:");

        jLabelNum1.setText("Número 1:");

        jTextFieldNum1.setName("Número 1"); // NOI18N

        jLabelNum2.setText("Número 2:");

        jSpinnerNum2.setModel(new javax.swing.SpinnerNumberModel());

        jButtonCalcular.setBackground(new java.awt.Color(0, 153, 153));
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNum1)
                    .addComponent(jLabelOperacion)
                    .addComponent(jLabelNum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerNum2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxOperacion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOperacionImg, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOperacion))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNum1)
                    .addComponent(jTextFieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNum2)
                    .addComponent(jSpinnerNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonCalcular))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelOperacionImg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(validationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        if (!divisionNum2Correcta()) {
            return;
        }
        double resultado = calcularResultado();
        Operacion operacion = new Operacion(jComboBoxOperacion.getSelectedItem().toString(), Integer.parseInt(jTextFieldNum1.getText()), Integer.parseInt(jSpinnerNum2.getValue().toString()), resultado);
        JOptionPane.showMessageDialog(this, "El resultado de la " + jComboBoxOperacion.getSelectedItem().toString() + " es: " + resultado, "Resultado", JOptionPane.INFORMATION_MESSAGE);

        LogicaOperaciones.addOperacion(operacion);
        dispose();
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jComboBoxOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperacionActionPerformed
        ImageIcon imgOriginal;
        String operacion = jComboBoxOperacion.getSelectedItem().toString();
        // Selecciona la imagen según la operación
        switch (operacion.toLowerCase()) {
            case "suma":
                imgOriginal = new ImageIcon(getClass().getResource("/simulacroCalculadora/gui/imgs/suma.png"));
                break;
            case "resta":
                imgOriginal = new ImageIcon(getClass().getResource("/simulacroCalculadora/gui/imgs/resta.png"));
                break;
            case "multiplicación":
                imgOriginal = new ImageIcon(getClass().getResource("/simulacroCalculadora/gui/imgs/multiplicacion.png"));
                break;
            case "división":
                imgOriginal = new ImageIcon(getClass().getResource("/simulacroCalculadora/gui/imgs/division.png"));
                break;
            case "potencia":
                imgOriginal = new ImageIcon(getClass().getResource("/simulacroCalculadora/gui/imgs/potencia.png"));
                break;
            default:
                throw new AssertionError();
        }
        Image img = imgOriginal.getImage();
        // Escala la imagen al tamaño del jLabel
        Image scaledImg = img.getScaledInstance(jLabelOperacionImg.getWidth(), jLabelOperacionImg.getHeight(), java.awt.Image.SCALE_SMOOTH);
        jLabelOperacionImg.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_jComboBoxOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogOperaciones dialog = new JDialogOperaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox<String> jComboBoxOperacion;
    private javax.swing.JLabel jLabelNum1;
    private javax.swing.JLabel jLabelNum2;
    private javax.swing.JLabel jLabelOperacion;
    private javax.swing.JLabel jLabelOperacionImg;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSpinner jSpinnerNum2;
    private javax.swing.JTextField jTextFieldNum1;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables

    private void validarDatos() {
        jButtonCalcular.setEnabled(false);
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextFieldNum1, StringValidators.REQUIRE_VALID_INTEGER);
        group.add(jTextFieldNum1, StringValidators.REQUIRE_NON_EMPTY_STRING);

        validationPanel.addChangeListener((ChangeEvent e) -> {
            if (validationPanel.getProblem() == null) {
                jButtonCalcular.setEnabled(true);
            } else {
                jButtonCalcular.setEnabled(false);
            }
        });

    }

    private boolean divisionNum2Correcta() {
        int num2 = Integer.parseInt(jSpinnerNum2.getValue().toString());
        String operacion = jComboBoxOperacion.getSelectedItem().toString();

        if (operacion.equalsIgnoreCase("división") && num2 == 0) {
            JOptionPane.showMessageDialog(this, "No se puede dividir entre 0, cambia la operación o el segundo número", "ERROR DIVISIÓN", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * Calcula el resultado de la operación
     *
     * @return
     */
    private double calcularResultado() {
        String operacion = jComboBoxOperacion.getSelectedItem().toString();
        int num1 = Integer.parseInt(jTextFieldNum1.getText());
        int num2 = Integer.parseInt(jSpinnerNum2.getValue().toString());
        double resultado = 0;
        switch (operacion.toLowerCase()) {
            case "suma":
                resultado = num1 + num2;
                break;
            case "resta":
                resultado = num1 - num2;
                break;
            case "multiplicación":
                resultado = num1 * num2;
                break;
            case "división":
                resultado = num1 / num2;
                break;
            case "potencia":
                resultado = Math.pow(num1, num2);
                break;
        }

        return resultado;
    }
}
