/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simulacroCalculadora.gui;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import simulacroCalculadora.dto.Operacion;
import simulacroCalculadora.logica.LogicaOperaciones;

/**
 *
 * @author Robert
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        cambiarIconoApp();
        mostrarLookAndFeel();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPpal = new javax.swing.JPanel();
        jPanelTema = new javax.swing.JPanel();
        jLabelTema = new javax.swing.JLabel();
        jComboLookAndFeel = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOperaciones = new javax.swing.JTable();
        jButtonEliminarFila = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOperaciones = new javax.swing.JMenu();
        jMenuItemNuevaOperacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTema.setLayout(new java.awt.GridLayout());

        jLabelTema.setText("Tema:");
        jPanelTema.add(jLabelTema);

        jComboLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLookAndFeelActionPerformed(evt);
            }
        });
        jPanelTema.add(jComboLookAndFeel);

        jTableOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableOperaciones);

        jButtonEliminarFila.setBackground(new java.awt.Color(204, 0, 0));
        jButtonEliminarFila.setText("Eliminar fila");
        jButtonEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPpalLayout = new javax.swing.GroupLayout(jPanelPpal);
        jPanelPpal.setLayout(jPanelPpalLayout);
        jPanelPpalLayout.setHorizontalGroup(
            jPanelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPpalLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButtonEliminarFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(183, 183, 183))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPpalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );
        jPanelPpalLayout.setVerticalGroup(
            jPanelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPpalLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEliminarFila)
                .addGap(32, 32, 32))
            .addGroup(jPanelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPpalLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jPanelTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        jMenuOperaciones.setText("Operaciones");

        jMenuItemNuevaOperacion.setText("Nueva operación");
        jMenuItemNuevaOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaOperacionActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemNuevaOperacion);

        jMenuBar.add(jMenuOperaciones);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFilaActionPerformed
        if (LogicaOperaciones.getListaOperaciones().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aún no hay operaciones para eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        eliminarOperacion();
    }//GEN-LAST:event_jButtonEliminarFilaActionPerformed

    /**
     * Abre el JDialog de operaciones
     *
     * @param evt
     */
    private void jMenuItemNuevaOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaOperacionActionPerformed
        JDialogOperaciones operacionesDialog = new JDialogOperaciones(this, true);
        operacionesDialog.setVisible(true);
        refrescarDatosTabla();
    }//GEN-LAST:event_jMenuItemNuevaOperacionActionPerformed

    private void jComboLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLookAndFeelActionPerformed
        try {
            UIManager.LookAndFeelInfo lookAndFeel = UIManager.getInstalledLookAndFeels()[jComboLookAndFeel.getSelectedIndex()];
            UIManager.setLookAndFeel(lookAndFeel.getClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(this, "Error asignando Look And Feel", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboLookAndFeelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarFila;
    private javax.swing.JComboBox<String> jComboLookAndFeel;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemNuevaOperacion;
    private javax.swing.JMenu jMenuOperaciones;
    private javax.swing.JPanel jPanelPpal;
    private javax.swing.JPanel jPanelTema;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOperaciones;
    // End of variables declaration//GEN-END:variables

    /**
     * Inicializa la tabla y sus componentes
     */
    private void inicializarTabla() {
        // Inicio dtm
        dtm = new DefaultTableModel() {
            @Override
            public Class getColumnClass(int column) {
                // Columna 3 (índice 3, la cuarta columna: "Resultado")
                if (column == 3) {
                    return Double.class; // Indica que los datos en esta columna son Double
                }
                // Para las otras columnas, mantiene el tipo Object (String por defecto)
                return Object.class;
            }
        };

        String[] titulos = new String[]{"Operación", "Num 1", "Num 2", "Resultado"};
        dtm.setColumnIdentifiers(titulos);
        jTableOperaciones.setModel(dtm);

        // Sorter
        TableRowSorter<TableModel> sorter = new TableRowSorter(jTableOperaciones.getModel());
        jTableOperaciones.setRowSorter(sorter);

        // Orden inicial
        List<RowSorter.SortKey> sortkeys = new ArrayList<>();
        sortkeys.add(new RowSorter.SortKey(3, SortOrder.DESCENDING)); // Columna resultado descendente
        sorter.setSortKeys(sortkeys);

        // Refrescamos tabla
        refrescarDatosTabla();

    }

    // Carga y refresca los datos de la tabla
    private void refrescarDatosTabla() {
        // Borra todas las filas
        dtm.setRowCount(0);

        // Llena el modelo con los datos actualizados
        LogicaOperaciones.getListaOperaciones().forEach(o -> dtm.addRow(new Object[]{o.getNombre(), o.getNum1(), o.getNum2(), o.getResultado()}));

        // Reordenamos los datos
        RowSorter<? extends TableModel> sorter = jTableOperaciones.getRowSorter();
        if (sorter != null) {
            // Usamos el cast al tipo concreto para acceder al método sort()
            ((TableRowSorter<?>) sorter).sort();
        }
    }

    /**
     * Muestra los Look And Feel del sistema en el Combo Box
     */
    private void mostrarLookAndFeel() {
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels()) {
            dcm.addElement(lfi.getName());
        }
        jComboLookAndFeel.setModel(dcm);
    }

    /**
     * Cambia el icono de la app
     */
    private void cambiarIconoApp() {
        // Cargamos la imagen
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/simulacroCalculadora/gui/imgs/icono.png"));

        // La asiganamos a Image
        Image iconoImagen = iconoApp.getImage();

        // La enlazamos al icono de la app
        this.setIconImage(iconoImagen);
    }

    /**
     * Elimina la operación deseada
     */
    private void eliminarOperacion() {
        String operacionBorrar = JOptionPane.showInputDialog(this, "Introduce la operación a eliminar", "Operación a eliminar", JOptionPane.QUESTION_MESSAGE);
        if (operacionBorrar == null) {
            JOptionPane.showMessageDialog(this, "Eliminación cancelada", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        } else if (operacionBorrar.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No has introducido nada", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String resultadoBorrar = JOptionPane.showInputDialog(this, "Introduce el resultado de la operación", "Operación a eliminar", JOptionPane.QUESTION_MESSAGE);
            double resultado = Double.parseDouble(resultadoBorrar);

            Operacion operacion = LogicaOperaciones.getListaOperaciones().stream()
                    .filter(h -> h.getNombre().equalsIgnoreCase(operacionBorrar) && h.getResultado() == resultado)
                    .findFirst().orElse(null);
            if (operacion == null) {
                JOptionPane.showMessageDialog(this, "No hay ninguna operación con esos datos", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else {
                int decisionBorrar = JOptionPane.showConfirmDialog(this, "¿Estás seguro de borrar la operación?", "¿Seguro?", JOptionPane.YES_NO_OPTION);
                if (decisionBorrar == JOptionPane.YES_OPTION) {
                    LogicaOperaciones.getListaOperaciones().remove(operacion);
                    JOptionPane.showMessageDialog(this, "De acuerdo, eliminamos"
                            + " la operación " + operacion.getNombre() + " con resultado " + operacion.getResultado(), "Operación borrada", JOptionPane.INFORMATION_MESSAGE);
                    refrescarDatosTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Sabía que no querías borrar "
                            + "la operación " + operacion.getNombre() + " con resultado " + operacion.getResultado(), "Operación NO borrada", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        }
    }
}
